language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:~1.0 --no-update --dev
  - composer install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls
